name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container: brorabbit/miot-build-ubuntu:1

    steps:
    - uses: actions/checkout@v2
    - name: Build C++
      run: ./scripts/build_cpp.sh release gcc make
